__author__ = 'vagrant'
# -*- coding: utf-8 -*-

from CourseConfiguration import courseConfiguration
from SupplementalVocabularyCourseESLSPAco import createUnitNumbers

projectName = "supplementalVocabCoursesESLCMNcn"

languageDict = [
    ["x for Chinese speakers", "English"],
]
unitMap = {
    "见面与问候": ["Meeting-and-Greeting-1",
              "Meeting-and-Greeting-2"],
    "获取语言学习的帮助": ["Communication-Facilitation-1",
                  "Communication-Facilitation-2",
                  "Communication-Facilitation-3",
                  "Communication-Facilitation-4",
                  "Communication-Facilitation-5",
                  "Communication-Facilitation-6",
                  "Communication-Facilitation-7"],
    "获取更多语言学习的帮助": ["Helper-Relationship",
                    "Language-Learning-Facilitation-1",
                    "Language-Learning-Facilitation-2",
                    "Translation-Facilitation"],
    "礼貌交谈": ["Polite-Conversation-1",
             "Polite-Conversation-2",
             "Polite-Conversation-3",
             "Useful-Expressions"],
    "形状和颜色": ["Shapes",
              "Colors"],
    "衣服": ["Clothing-1",
           "Clothing-2",
           "Clothing-3"],
    "购物与商店": ["Shopping-Stores",
              "Shopping-1",
              "Shopping-2",
              "Shopping-3",
              "Shopping-4",
              "Shopping-5"],
    "房子和公寓": ["House-Apartment-1",
              "House-Apartment-2"],
    "房间": ["Living-Room",
           "Dining-Room",
           "Kitchen",
           "Bathroom-1",
           "Bathroom-2",
           "Bedroom"],
    "家庭": ["Family-1",
           "Family-2",
           "Family-3",
           "Family-4"],
    "办公室与职业": ["Office-1",
               "Office-2",
               "Professions-1",
               "Professions-2"],
    "身体部位": ["Parts-of-the-Body-1",
             "Parts-of-the-Body-2"],
    "紧急情况": ["Emergencies-1",
             "Emergencies-2",
             "Emergencies-3",
             "Emergencies-4",
             "Emergencies-5"],
    "地方与问路": ["Places-1",
              "Places-2",
              "Asking-for-Directions-1",
              "Asking-for-Directions-2"],
    "学校": ["School-1",
           "School-2",
           "School-3"],
    "乐器": ["Musical-Instruments-1",
           "Musical-Instruments-2"],
    "娱乐": ["Recreation-1",
           "Recreation-2",
           "Recreation-3"],
    "自然界": ["Nature-1",
            "Nature-2"],
    "动物": ["Animals-1",
           "Animals-2"],
    "食物1": ["Meals",
            "Beverages",
            "Fruit",
            "Vegetables",
            "Grains"],
    "食物2": ["Dairy",
            "Meat",
            "Seafood",
            "Spices-Condiments",
            "Dessert"],
    "去餐馆": ["At-the-Restaurant-1",
            "At-the-Restaurant-2",
            "At-the-Restaurant-3",
            "At-the-Restaurant-4",
            "At-the-Restaurant-5"],
    "语言": ["Languages-1",
           "Languages-2",
           "Languages-3",
           "Languages-4"],
    "国名": ["Continents",
           "Countries-1",
           "Countries-2",
           "Countries-3"],
    "旅游": ["Travel-1",
           "Travel-2",
           "Travel-3",
           "Travel-4",
           "Travel-5"],
    "买票": ["Buying-Tickets-1",
           "Buying-Tickets-2",
           "Buying-Tickets-3"],
    "乘出租车": ["Taking-a-Taxi-1",
             "Taking-a-Taxi-2",
             "Taking-a-Taxi-3"],
    "住旅馆": ["At-the-Hotel-1",
            "At-the-Hotel-2",
            "At-the-Hotel-3",
            "At-the-Hotel-4"],
    "去银行": ["Going-to-the-Bank-1",
            "Going-to-the-Bank-2",
            "Going-to-the-Bank-3",
            "Going-to-the-Bank-4"],
    "数字": ["Numbers-Cardinal-1",
           "Numbers-Cardinal-2",
           "Numbers-Cardinal-3",
           "Numbers-Cardinal-4",
           "Numbers-Ordinal",
           "Numbers-Other"],
    "星期和时间": ["Days-of-the-Week-1",
              "Days-of-the-Week-2",
              "Time-1",
              "Time-2",
              "Asking-the-Time"],
    "季节和天气": ["Months",
              "Seasons",
              "Weather-1",
              "Weather-2"],
    "人称代词 和 所有格形容词": ["Personal-Pronouns",
                      "Possessive-Adjectives",
                      "Conjunctions"],
    "形容词 和 副词": ["Adjectives-1",
                 "Adjectives-2",
                 "Adjectives-3",
                 "Adverbs"],
    "动词": ["Verbs-1",
           "Verbs-2",
           "Verbs-3",
           "Verbs-4",
           "Verbs-5",
           "Verbs-6",
           "Verbs-7",
           "Verbs-8"],
    "介词": ["Prepositions-1",
           "Prepositions-2",
           "Prepositions-3",
           "Prepositions-4"]
}
unitNameList = unitMap.keys()


def createSVCConfiguration():
    """
    takes the above information and builds a course object for the rest of the scripts

    :return: a filled out course object
    """
    configObject = courseConfiguration()
    configObject.projectName = projectName
    configObject.unitNameList = unitNameList
    configObject.languageDict = languageDict
    configObject.unitMap = unitMap
    configObject.unitObjectives = unitObjectives
    configObject.lessonOrder = lessonOrder
    configObject.unitNumbers = createUnitNumbers(unitNameList)
    configObject.lessonToList = lessonNameToListNameMap
    configObject.isESLTrue = isESLTrue

    return configObject